### ISSUE TITLE
Random code comment

### ISSUE THREAD

**Issue by yan-zaretskiy** [vinomarkus/Monograph-20-Examples#1]
Hi there!

Since you are learning Python, I thought you wouldn't object to minor code suggestions.

In your first notebook you have:
```
M = [16.04, 30.07, 44.09]
x = [0.49, 0.38, 0.13]
# ...
ncomps = len(M)
m = [x[i]*M[i] for i in range(ncomps)]
# ...
```
The standard Pythonic way of computing `x` would instead be:
```
M = [16.04, 30.07, 44.09]
x = [0.49, 0.38, 0.13]
m = [xi * Mi for xi, Mi in zip(x, M)]
```

**Comment by mwburgoyne** [comment]
Many thanks - good to know

And here I was thinking it was reasonably Pythonic already - there's always a simpler way! I've done it that way so many times through this code, that I don't think I'll go through and update them all, but will  try to use it future

Regs,
Mark
